name: Secret Scanning Mock Check

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate secret scanning response
        run: |
          echo "🔍 Using mock GitHub secret scanning response..."

          # Simulated response (real use would be a curl call)
          response='[
            {
              "number": 1,
              "created_at": "2020-11-06T18:18:30Z",
              "url": "https://api.github.com/repos/owner/repo/secret-scanning/alerts/1",
              "html_url": "https://github.com/owner/repo/security/secret-scanning/1",
              "secret_type": "mailchimp_api_key",
              "secret_type_display_name": "Mailchimp API Key",
              "state": "open"
            }
          ]'

          echo "📦 Raw API response:"
          echo "$response" | jq .

          # Count open alerts
          count=$(echo "$response" | jq '[.[] | select(.state == "open")] | length')

          if [ "$count" -gt 0 ]; then
            echo "❌ $count open secret scanning alerts found:"
            echo "$response" | jq -r '.[] | select(.state == "open") | "- Type: \(.secret_type_display_name)\n  URL: \(.html_url)\n  Created: \(.created_at)"'
            exit 1
          else
            echo "✅ No open alerts found."
          fi