name: Secret Scanning Gate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open secret scanning alerts
        id: scan
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Checking for open secret scanning alerts in $REPO..."
          alerts=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/secret-scanning/alerts?state=open")

          echo "📦 Raw API Response:"
          cat "$api_response"
          echo ""

          open_count=$(echo "$alerts" | jq 'length')

          echo "Found $open_count open secret alerts."

          if [ "$open_count" -gt 0 ]; then
            echo "❌ Open secrets found. Failing workflow."
            exit 1
          else
            echo "✅ No open secrets found."
          fi
