name: Secret Scanning Gate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open secret scanning alerts
        id: scan
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Or use GH_PAT for private repos
          REPO: ${{ github.repository }}
        run: |
          echo "Checking for open secret scanning alerts in $REPO..."
          alerts=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/secret-scanning/alerts?state=open")

          open_count=$(echo "$alerts" | jq 'length')

          if [ "$open_count" -gt 0 ]; then
            echo "❌ Found $open_count open secret scanning alerts:"
            echo "$alerts" | jq -r '.[].html_url'
            exit 1
          else
            echo "✅ No open secrets found."
          fi