name: Secret Scanning Gate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open secret scanning alerts
        id: scan
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "🔍 Calling GitHub Secret Scanning Alerts API for $REPO..."

          # Make API call and capture both response body and HTTP status
          api_response=$(mktemp)
          status_code=$(curl -s -w "%{http_code}" -o "$api_response" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/secret-scanning/alerts?state=open")

          echo "📦 Raw API Response:"
          cat "$api_response"
          echo ""

          # Fail if status code is not 200
          if [ "$status_code" -ne 200 ]; then
            echo "❌ API call failed with status code $status_code"
            exit 1
          fi

          # Count and handle open secrets
          open_count=$(jq 'length' < "$api_response")
          if [ "$open_count" -gt 0 ]; then
            echo "❌ $open_count open secret scanning alerts found. Failing the workflow."
            exit 1
          else
            echo "✅ No open secrets found."
          fi
