name: Secret Scanning Gate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open secret scanning alerts
        id: scan
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Calling GitHub Secret Scanning Alerts API for $REPO..."

          response=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
                          -H "Accept: application/vnd.github+json" \
                          "https://api.github.com/repos/$REPO/secret-scanning/alerts?state=open")

          echo "🔍 Raw API response:"
          echo "$response"

          # Try to parse and count the number of alerts
          count=$(echo "$response" | jq 'length' 2>/dev/null)

          # Check if jq failed (invalid JSON)
          if [ -z "$count" ]; then
            echo "❌ Failed to parse API response. Invalid JSON?"
            exit 1
          fi

          if [ "$count" -gt 0 ]; then
            echo "❌ $count open secret scanning alerts found. Failing the workflow."
            exit 1
          else
            echo "✅ No open secret scanning alerts."
          fi
